/**
 * Canonical public origin for SEO: canonical tags, sitemap, robots, Open Graph
 * and JSON-LD all derive from this one value.
 *
 * It used to be hardcoded as https://orion.sathyabama.ac.in — a hostname with
 * no DNS record — so every canonical and sitemap URL pointed search engines at
 * a dead domain. This is deliberately NOT read from NEXT_PUBLIC_SITE_URL: that
 * variable is http://localhost:3000 in .env.local, and a local build would bake
 * localhost into every canonical tag. If a custom domain is attached, change it
 * here (and 301 the workers.dev host to it).
 */
export const SITE_URL = 'https://orion-hackathon.gopinath2638.workers.dev';

export const SITE_NAME = 'ORION 1.0';

/** 1200×630 social card, generated by scripts/generate_og_image.mjs. */
export const OG_IMAGE = {
  url: '/og-image.png',
  width: 1200,
  height: 630,
  alt: 'ORION 1.0 — 24-Hour National Level Hackathon by Microsoft Club SIST, Sathyabama Chennai. ₹1,00,000 prize pool.',
};

/** Bumped by hand when public page content changes; a per-request timestamp teaches crawlers to ignore lastmod. */
export const CONTENT_LAST_MODIFIED = '2026-09-13';

export const SOCIAL_PROFILES = ['https://www.instagram.com/orion1.0_'];
