/**
 * Canonical public origin for SEO: canonical tags, sitemap, robots, Open Graph
 * and JSON-LD all derive from this one value.
 *
 * It must be the host that answers 200, not one that redirects: msclubsist.in
 * 308s to www.msclubsist.in, and a canonical pointing at a redirect is a mixed
 * signal Google may ignore. (It was once orion.sathyabama.ac.in, which has no
 * DNS record at all.) Not read from NEXT_PUBLIC_SITE_URL, which is
 * http://localhost:3000 in .env.local and would leak into local builds.
 */
export const SITE_URL = 'https://www.msclubsist.in';

export const SITE_NAME = 'ORION 1.0';

/** 1200×630 social card, generated by scripts/generate_og_image.mjs. */
export const OG_IMAGE = {
  url: '/og-image.png',
  width: 1200,
  height: 630,
  alt: 'ORION 1.0 — 24-Hour National Level Hackathon by Microsoft Club SIST, Sathyabama Chennai. ₹1,00,000 prize pool.',
};

/** Bumped by hand when public page content changes; a per-request timestamp teaches crawlers to ignore lastmod. */
export const CONTENT_LAST_MODIFIED = '2026-09-13';

export const SOCIAL_PROFILES = ['https://www.instagram.com/orion1.0_'];
